/**
 * AUTO-GENERATED by scripts/sync-design-tokens.mjs — do not edit by hand.
 * Source: design/tokens.json
 * Run: npm run sync:design
 */
export const PENCIL_APPLE_CSS_VARS = {
  bg: "--apple-bg",
  surface: "--apple-surface",
  text: "--apple-text",
  textSecondary: "--apple-text-secondary",
  link: "--apple-link",
  separator: "--apple-separator",
  cardBg: "--apple-card-bg",
  navBg: "--apple-nav-bg",
} as const;

export const PENCIL_APPLE_LIGHT_COLORS = {
  "bg": "#ffffff",
  "surface": "#fbfbfd",
  "text": "#1d1d1f",
  "textSecondary": "#6e6e73",
  "link": "#0066cc",
  "separator": "rgba(0, 0, 0, 0.08)",
  "cardBg": "#ffffff",
  "navBg": "rgba(251, 251, 253, 0.8)"
} as const;

export const PENCIL_LAYOUT_SIZES = {
  gridUnit: 8,
  insetGroupRadius: 16,
  sheetRadius: 28,
  touchMinHeight: 44,
  listRowMinHeight: 52,
  headerHeight: 48,
  tabBarHeight: 56,
  contentMaxWidth: 980,
} as const;

export const PENCIL_PEN_FILES = {
  dashboard: "design/screens/dashboard.pen",
  groups: "design/screens/groups.pen",
  groupDetail: "design/screens/group-detail.pen",
  settings: "design/screens/settings.pen",
  login: "design/screens/login.pen",
  landing: "design/screens/landing.pen",
  tokensJson: "design/tokens.json",
} as const;
